name: CI Checks

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Formatting of Files
        uses: FreeRTOS/CI-CD-Github-Actions/formatting@main
        with:
          exclude-dirs: Drivers

  spell-check:
      runs-on: ubuntu-latest
      steps:
        - name: Clone This Repo
          uses: actions/checkout@v3
        - name: Run spellings check
          uses: FreeRTOS/CI-CD-Github-Actions/spellings@main

  link-verifier:
    runs-on: ubuntu-latest
    steps:
      - name: Clone This Repo
        uses: actions/checkout@v3
      - name: Link Verification
        uses: FreeRTOS/CI-CD-Github-Actions/link-verifier@main

  verify-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Run manifest verifier
        uses: FreeRTOS/CI-CD-GitHub-Actions/manifest-verifier@main
        with:
          path: ./
          fail-on-incorrect-version: true

  git-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout awslabs/git-secrets
        uses: actions/checkout@v3
        with:
          repository: awslabs/git-secrets
          ref: master
          path: git-secrets
      - name: Install git-secrets
        run: cd git-secrets && sudo make install && cd ..
      - name: Run git-secrets
        run: |
          git-secrets --register-aws
          git-secrets --scan

  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch HEAD revision
        run: git fetch origin
      - name: Install python pip
        run:  sudo apt-get install python3-pip
      - name: Install virtualenv
        run: pip install virtualenv
      - name: create virtual environment
        run: |
          virtualenv venv
          source venv/bin/activate
      - name: install pre-commit package via pip
        run: |
          source venv/bin/activate
          pip install pre-commit
      - name: Run pre-commit hooks
        run: |
          source venv/bin/activate
          if [ -n "${GITHUB_BASE_REF}" ]; then
            BASE_REF="origin/${GITHUB_BASE_REF}"
          elif [ "${GITHUB_REF_NAME}" == "main" ] || [ "${GITHUB_REF_NAME}" == "dev" ]; then
            BASE_REF=""
          else
            BASE_REF="$(git symbolic-ref --short refs/remotes/origin/HEAD)"
          fi
          if [ -n "${BASE_REF}" ]; then
            pre-commit run --from-ref "${BASE_REF}" --to-ref "${GITHUB_SHA}" --show-diff
          else
            pre-commit run --all --show-diff
          fi
